# Generated by Django 5.0.6 on 2026-06-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_complete',
            field=models.BooleanField(default=False),
        ),
    ]
