# Generated by Django 5.0.6 on 2026-07-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_userprofile_active_draft_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="category_label",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
