# Generated by Django 5.0.6 on 2026-07-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_add_skill_category_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="eportfolio_url",
            field=models.URLField(blank=True),
        ),
    ]
