"""
Skill resource descriptor catalog for the Skill Gap Analysis feature.

Pure Python: no I/O, no ORM, no network calls.
Provides a curated mapping from skill tokens to structured learning resource descriptors.
Token keys match the tokens produced by extract_skill_gaps() in match_scoring.py.
"""
from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class SkillResourceDescriptor:
    display_name: str
    category: str
    description: str
    resource_type: str
    url: str
    prerequisites: tuple[str, ...] = field(default_factory=tuple)


VALID_CATEGORIES = frozenset({
    "programming", "framework", "database", "cloud",
    "devops", "tool", "soft_skill", "other",
})

VALID_RESOURCE_TYPES = frozenset({"docs", "course", "certification", "practice"})

SKILL_RESOURCES: dict[str, SkillResourceDescriptor] = {
    # ── Programming languages ────────────────────────────────────────────────
    "python": SkillResourceDescriptor(
        display_name="Python",
        category="programming",
        description="General-purpose interpreted language widely used in web, data, and automation.",
        resource_type="docs",
        url="https://docs.python.org/",
        prerequisites=(),
    ),
    "java": SkillResourceDescriptor(
        display_name="Java",
        category="programming",
        description="Object-oriented compiled language for enterprise and Android development.",
        resource_type="docs",
        url="https://dev.java/",
        prerequisites=(),
    ),
    "javascript": SkillResourceDescriptor(
        display_name="JavaScript",
        category="programming",
        description="Dynamic scripting language for web browsers and server-side via Node.js.",
        resource_type="docs",
        url="https://developer.mozilla.org/docs/Web/JavaScript",
        prerequisites=(),
    ),
    "typescript": SkillResourceDescriptor(
        display_name="TypeScript",
        category="programming",
        description="Typed superset of JavaScript that compiles to plain JavaScript.",
        resource_type="docs",
        url="https://www.typescriptlang.org/docs/",
        prerequisites=("javascript",),
    ),
    "ruby": SkillResourceDescriptor(
        display_name="Ruby",
        category="programming",
        description="Dynamic, expressive scripting language optimised for developer productivity.",
        resource_type="docs",
        url="https://www.ruby-lang.org/en/documentation/",
        prerequisites=(),
    ),
    "php": SkillResourceDescriptor(
        display_name="PHP",
        category="programming",
        description="Server-side scripting language for web development.",
        resource_type="docs",
        url="https://www.php.net/manual/en/",
        prerequisites=(),
    ),
    "swift": SkillResourceDescriptor(
        display_name="Swift",
        category="programming",
        description="Apple's language for iOS, macOS, and server-side development.",
        resource_type="docs",
        url="https://www.swift.org/documentation/",
        prerequisites=(),
    ),
    "kotlin": SkillResourceDescriptor(
        display_name="Kotlin",
        category="programming",
        description="Modern JVM language for Android and server-side development.",
        resource_type="docs",
        url="https://kotlinlang.org/docs/",
        prerequisites=(),
    ),
    "go": SkillResourceDescriptor(
        display_name="Go",
        category="programming",
        description="Compiled language designed for efficient concurrent systems programming.",
        resource_type="docs",
        url="https://go.dev/doc/",
        prerequisites=(),
    ),
    "rust": SkillResourceDescriptor(
        display_name="Rust",
        category="programming",
        description="Systems programming language focused on memory safety and performance.",
        resource_type="docs",
        url="https://doc.rust-lang.org/book/",
        prerequisites=(),
    ),
    "scala": SkillResourceDescriptor(
        display_name="Scala",
        category="programming",
        description="JVM language combining object-oriented and functional programming.",
        resource_type="docs",
        url="https://docs.scala-lang.org/",
        prerequisites=("java",),
    ),
    "dart": SkillResourceDescriptor(
        display_name="Dart",
        category="programming",
        description="Client-optimised language for Flutter cross-platform development.",
        resource_type="docs",
        url="https://dart.dev/guides",
        prerequisites=(),
    ),
    "flutter": SkillResourceDescriptor(
        display_name="Flutter",
        category="framework",
        description="Google's UI toolkit for building natively compiled multi-platform apps.",
        resource_type="docs",
        url="https://docs.flutter.dev/",
        prerequisites=("dart",),
    ),
    "c": SkillResourceDescriptor(
        display_name="C",
        category="programming",
        description="Low-level systems programming language foundational to modern computing.",
        resource_type="docs",
        url="https://en.cppreference.com/w/c",
        prerequisites=(),
    ),
    # ── Web frameworks ───────────────────────────────────────────────────────
    "react": SkillResourceDescriptor(
        display_name="React",
        category="framework",
        description="Component-based UI library for building web interfaces.",
        resource_type="docs",
        url="https://react.dev/",
        prerequisites=("javascript",),
    ),
    "angular": SkillResourceDescriptor(
        display_name="Angular",
        category="framework",
        description="TypeScript-based full web framework maintained by Google.",
        resource_type="docs",
        url="https://angular.dev/",
        prerequisites=("typescript",),
    ),
    "vue": SkillResourceDescriptor(
        display_name="Vue",
        category="framework",
        description="Progressive JavaScript framework for building user interfaces.",
        resource_type="docs",
        url="https://vuejs.org/guide/",
        prerequisites=("javascript",),
    ),
    "nextjs": SkillResourceDescriptor(
        display_name="Next.js",
        category="framework",
        description="React framework for full-stack web applications with SSR and SSG.",
        resource_type="docs",
        url="https://nextjs.org/docs",
        prerequisites=("react",),
    ),
    "nodejs": SkillResourceDescriptor(
        display_name="Node.js",
        category="framework",
        description="JavaScript runtime for scalable server-side applications.",
        resource_type="docs",
        url="https://nodejs.org/docs/latest/",
        prerequisites=("javascript",),
    ),
    "django": SkillResourceDescriptor(
        display_name="Django",
        category="framework",
        description="Python web framework following the MVT pattern with batteries included.",
        resource_type="docs",
        url="https://docs.djangoproject.com/",
        prerequisites=("python",),
    ),
    "flask": SkillResourceDescriptor(
        display_name="Flask",
        category="framework",
        description="Lightweight Python micro web framework for simple APIs and apps.",
        resource_type="docs",
        url="https://flask.palletsprojects.com/",
        prerequisites=("python",),
    ),
    "fastapi": SkillResourceDescriptor(
        display_name="FastAPI",
        category="framework",
        description="Modern Python API framework with automatic OpenAPI docs and validation.",
        resource_type="docs",
        url="https://fastapi.tiangolo.com/",
        prerequisites=("python",),
    ),
    "spring": SkillResourceDescriptor(
        display_name="Spring",
        category="framework",
        description="Java enterprise application framework and ecosystem for microservices.",
        resource_type="docs",
        url="https://spring.io/learn",
        prerequisites=("java",),
    ),
    "rails": SkillResourceDescriptor(
        display_name="Ruby on Rails",
        category="framework",
        description="Full-stack web framework for rapid convention-over-configuration development.",
        resource_type="docs",
        url="https://guides.rubyonrails.org/",
        prerequisites=("ruby",),
    ),
    "laravel": SkillResourceDescriptor(
        display_name="Laravel",
        category="framework",
        description="Full-featured PHP web application framework with elegant syntax.",
        resource_type="docs",
        url="https://laravel.com/docs",
        prerequisites=("php",),
    ),
    "express": SkillResourceDescriptor(
        display_name="Express.js",
        category="framework",
        description="Minimal and flexible Node.js web application framework.",
        resource_type="docs",
        url="https://expressjs.com/",
        prerequisites=("nodejs",),
    ),
    # ── Cloud ────────────────────────────────────────────────────────────────
    "aws": SkillResourceDescriptor(
        display_name="AWS",
        category="cloud",
        description="Amazon's cloud platform: compute, storage, networking, and 200+ services.",
        resource_type="certification",
        url="https://aws.amazon.com/getting-started/",
        prerequisites=(),
    ),
    "azure": SkillResourceDescriptor(
        display_name="Azure",
        category="cloud",
        description="Microsoft's cloud platform for enterprise applications and hybrid cloud.",
        resource_type="certification",
        url="https://learn.microsoft.com/azure",
        prerequisites=(),
    ),
    "gcp": SkillResourceDescriptor(
        display_name="GCP",
        category="cloud",
        description="Google's cloud platform for scalable compute, ML, and data services.",
        resource_type="certification",
        url="https://cloud.google.com/docs",
        prerequisites=(),
    ),
    # ── DevOps & infrastructure ──────────────────────────────────────────────
    "docker": SkillResourceDescriptor(
        display_name="Docker",
        category="devops",
        description="Container runtime for packaging and deploying applications consistently.",
        resource_type="docs",
        url="https://docs.docker.com/get-started/",
        prerequisites=(),
    ),
    "kubernetes": SkillResourceDescriptor(
        display_name="Kubernetes",
        category="devops",
        description="Container orchestration platform for automating deployment and scaling.",
        resource_type="course",
        url="https://kubernetes.io/docs/tutorials/",
        prerequisites=("docker",),
    ),
    "terraform": SkillResourceDescriptor(
        display_name="Terraform",
        category="devops",
        description="Infrastructure-as-Code tool for provisioning cloud resources declaratively.",
        resource_type="docs",
        url="https://developer.hashicorp.com/terraform/intro",
        prerequisites=(),
    ),
    "ansible": SkillResourceDescriptor(
        display_name="Ansible",
        category="devops",
        description="Agentless automation tool for configuration management and provisioning.",
        resource_type="docs",
        url="https://docs.ansible.com/",
        prerequisites=(),
    ),
    "kafka": SkillResourceDescriptor(
        display_name="Apache Kafka",
        category="devops",
        description="Distributed event streaming platform for high-throughput data pipelines.",
        resource_type="docs",
        url="https://kafka.apache.org/documentation/",
        prerequisites=(),
    ),
    "rabbitmq": SkillResourceDescriptor(
        display_name="RabbitMQ",
        category="devops",
        description="Message broker for reliable asynchronous task queuing between services.",
        resource_type="docs",
        url="https://www.rabbitmq.com/tutorials",
        prerequisites=(),
    ),
    # ── Databases ────────────────────────────────────────────────────────────
    "sql": SkillResourceDescriptor(
        display_name="SQL",
        category="database",
        description="Structured Query Language for querying and managing relational databases.",
        resource_type="practice",
        url="https://www.w3schools.com/sql/",
        prerequisites=(),
    ),
    "postgresql": SkillResourceDescriptor(
        display_name="PostgreSQL",
        category="database",
        description="Open-source object-relational database with advanced SQL compliance.",
        resource_type="docs",
        url="https://www.postgresql.org/docs/",
        prerequisites=("sql",),
    ),
    "mysql": SkillResourceDescriptor(
        display_name="MySQL",
        category="database",
        description="Popular open-source relational database widely used in web applications.",
        resource_type="docs",
        url="https://dev.mysql.com/doc/",
        prerequisites=("sql",),
    ),
    "mongodb": SkillResourceDescriptor(
        display_name="MongoDB",
        category="database",
        description="Document-oriented NoSQL database for flexible, schema-less data storage.",
        resource_type="docs",
        url="https://www.mongodb.com/docs/",
        prerequisites=(),
    ),
    "redis": SkillResourceDescriptor(
        display_name="Redis",
        category="database",
        description="In-memory data store for caching, pub/sub, and session management.",
        resource_type="docs",
        url="https://redis.io/docs/",
        prerequisites=(),
    ),
    "elasticsearch": SkillResourceDescriptor(
        display_name="Elasticsearch",
        category="database",
        description="Distributed search and analytics engine for full-text and structured data.",
        resource_type="docs",
        url="https://www.elastic.co/docs/",
        prerequisites=(),
    ),
    # ── Protocols & API styles ───────────────────────────────────────────────
    "graphql": SkillResourceDescriptor(
        display_name="GraphQL",
        category="framework",
        description="Query language and runtime for APIs with a strongly-typed schema.",
        resource_type="docs",
        url="https://graphql.org/learn/",
        prerequisites=(),
    ),
    "grpc": SkillResourceDescriptor(
        display_name="gRPC",
        category="framework",
        description="High-performance RPC framework using Protocol Buffers for distributed services.",
        resource_type="docs",
        url="https://grpc.io/docs/",
        prerequisites=(),
    ),
    "rest": SkillResourceDescriptor(
        display_name="REST",
        category="other",
        description="Architectural style for designing stateless HTTP APIs.",
        resource_type="docs",
        url="https://restfulapi.net/",
        prerequisites=(),
    ),
    # ── ML & data ────────────────────────────────────────────────────────────
    "tensorflow": SkillResourceDescriptor(
        display_name="TensorFlow",
        category="framework",
        description="Google's open-source ML library for building and training neural networks.",
        resource_type="course",
        url="https://www.tensorflow.org/learn",
        prerequisites=("python",),
    ),
    "pytorch": SkillResourceDescriptor(
        display_name="PyTorch",
        category="framework",
        description="Facebook's dynamic ML framework popular in research and production.",
        resource_type="course",
        url="https://pytorch.org/tutorials/",
        prerequisites=("python",),
    ),
    "scikit": SkillResourceDescriptor(
        display_name="scikit-learn",
        category="framework",
        description="Machine learning library for classical algorithms and model evaluation.",
        resource_type="docs",
        url="https://scikit-learn.org/stable/user_guide.html",
        prerequisites=("python", "pandas"),
    ),
    "pandas": SkillResourceDescriptor(
        display_name="Pandas",
        category="framework",
        description="Data analysis and manipulation library for Python using DataFrames.",
        resource_type="docs",
        url="https://pandas.pydata.org/docs/",
        prerequisites=("python",),
    ),
    "spark": SkillResourceDescriptor(
        display_name="Apache Spark",
        category="framework",
        description="Unified analytics engine for large-scale distributed data processing.",
        resource_type="docs",
        url="https://spark.apache.org/docs/latest/",
        prerequisites=("python",),
    ),
    "hadoop": SkillResourceDescriptor(
        display_name="Hadoop",
        category="framework",
        description="Distributed storage and batch processing framework for big data.",
        resource_type="docs",
        url="https://hadoop.apache.org/docs/",
        prerequisites=(),
    ),
    # ── VCS & CI/CD ──────────────────────────────────────────────────────────
    "git": SkillResourceDescriptor(
        display_name="Git",
        category="tool",
        description="Distributed version control system for tracking code history.",
        resource_type="docs",
        url="https://git-scm.com/doc",
        prerequisites=(),
    ),
    "jenkins": SkillResourceDescriptor(
        display_name="Jenkins",
        category="tool",
        description="Open-source automation server for building CI/CD pipelines.",
        resource_type="docs",
        url="https://www.jenkins.io/doc/",
        prerequisites=("git",),
    ),
    "gitlab": SkillResourceDescriptor(
        display_name="GitLab",
        category="tool",
        description="DevOps platform combining version control, CI/CD, and project management.",
        resource_type="docs",
        url="https://docs.gitlab.com/",
        prerequisites=("git",),
    ),
    "github": SkillResourceDescriptor(
        display_name="GitHub",
        category="tool",
        description="Git hosting platform with Actions for CI/CD and open-source collaboration.",
        resource_type="docs",
        url="https://docs.github.com/",
        prerequisites=("git",),
    ),
    # ── OS & shell ───────────────────────────────────────────────────────────
    "linux": SkillResourceDescriptor(
        display_name="Linux",
        category="tool",
        description="Open-source Unix-like operating system for servers and development environments.",
        resource_type="docs",
        url="https://www.kernel.org/doc/",
        prerequisites=(),
    ),
    "bash": SkillResourceDescriptor(
        display_name="Bash",
        category="tool",
        description="Unix shell and scripting language for task automation and pipelines.",
        resource_type="docs",
        url="https://www.gnu.org/software/bash/manual/",
        prerequisites=("linux",),
    ),
    "powershell": SkillResourceDescriptor(
        display_name="PowerShell",
        category="tool",
        description="Microsoft's cross-platform shell and scripting language for automation.",
        resource_type="docs",
        url="https://learn.microsoft.com/powershell/",
        prerequisites=(),
    ),
    # ── Soft skills ──────────────────────────────────────────────────────────
    "leadership": SkillResourceDescriptor(
        display_name="Leadership",
        category="soft_skill",
        description="Guiding and motivating a team toward shared goals and long-term vision.",
        resource_type="practice",
        url="https://hbr.org/topic/subject/leadership",
        prerequisites=(),
    ),
    "mentoring": SkillResourceDescriptor(
        display_name="Mentoring",
        category="soft_skill",
        description="Providing guidance and career support to help others grow professionally.",
        resource_type="practice",
        url="https://www.mentoring.org/",
        prerequisites=(),
    ),
    "mentorship": SkillResourceDescriptor(
        display_name="Mentorship",
        category="soft_skill",
        description="Ongoing developmental relationship between experienced and junior professionals.",
        resource_type="practice",
        url="https://www.mentoring.org/",
        prerequisites=(),
    ),
    "coaching": SkillResourceDescriptor(
        display_name="Coaching",
        category="soft_skill",
        description="Using structured conversations to help others develop skills and reach goals.",
        resource_type="practice",
        url="https://coachingfederation.org/",
        prerequisites=(),
    ),
    "ownership": SkillResourceDescriptor(
        display_name="Ownership",
        category="soft_skill",
        description="Taking full responsibility for outcomes and driving work to completion.",
        resource_type="practice",
        url="https://hbr.org/2016/09/the-elements-of-good-judgment",
        prerequisites=(),
    ),
    "teamwork": SkillResourceDescriptor(
        display_name="Teamwork",
        category="soft_skill",
        description="Collaborating effectively with others toward shared objectives.",
        resource_type="practice",
        url="https://hbr.org/topic/subject/managing-people",
        prerequisites=(),
    ),
    "collaboration": SkillResourceDescriptor(
        display_name="Collaboration",
        category="soft_skill",
        description="Working jointly with colleagues across functions to achieve shared outcomes.",
        resource_type="practice",
        url="https://hbr.org/topic/subject/collaboration",
        prerequisites=(),
    ),
    "communication": SkillResourceDescriptor(
        display_name="Communication",
        category="soft_skill",
        description="Clearly conveying ideas and information to diverse audiences.",
        resource_type="practice",
        url="https://hbr.org/topic/subject/communication",
        prerequisites=(),
    ),
    "empathy": SkillResourceDescriptor(
        display_name="Empathy",
        category="soft_skill",
        description="Understanding and sharing the perspectives and feelings of colleagues and customers.",
        resource_type="practice",
        url="https://hbr.org/2021/02/connect-to-what-matters",
        prerequisites=(),
    ),
    "facilitation": SkillResourceDescriptor(
        display_name="Facilitation",
        category="soft_skill",
        description="Guiding groups through discussions and structured decision-making processes.",
        resource_type="course",
        url="https://www.iaf-world.org/",
        prerequisites=(),
    ),
    "negotiation": SkillResourceDescriptor(
        display_name="Negotiation",
        category="soft_skill",
        description="Reaching mutually beneficial agreements through structured discussion.",
        resource_type="course",
        url="https://www.coursera.org/learn/negotiation",
        prerequisites=(),
    ),
    "persuasion": SkillResourceDescriptor(
        display_name="Persuasion",
        category="soft_skill",
        description="Influencing others' views and decisions through evidence and clear communication.",
        resource_type="practice",
        url="https://hbr.org/topic/subject/persuading-others",
        prerequisites=(),
    ),
    "networking": SkillResourceDescriptor(
        display_name="Networking",
        category="soft_skill",
        description="Building professional relationships that create mutual value over time.",
        resource_type="practice",
        url="https://hbr.org/2016/05/learn-to-love-networking",
        prerequisites=(),
    ),
    "initiative": SkillResourceDescriptor(
        display_name="Initiative",
        category="soft_skill",
        description="Proactively identifying and acting on opportunities without being asked.",
        resource_type="practice",
        url="https://hbr.org/2014/01/take-initiative-dont-be-passive",
        prerequisites=(),
    ),
    "accountability": SkillResourceDescriptor(
        display_name="Accountability",
        category="soft_skill",
        description="Accepting responsibility for one's actions and consistently delivering on commitments.",
        resource_type="practice",
        url="https://hbr.org/topic/subject/accountability",
        prerequisites=(),
    ),
    "adaptability": SkillResourceDescriptor(
        display_name="Adaptability",
        category="soft_skill",
        description="Adjusting effectively to new situations, changing priorities, and unexpected challenges.",
        resource_type="practice",
        url="https://hbr.org/2021/02/become-more-adaptable",
        prerequisites=(),
    ),
    "resilience": SkillResourceDescriptor(
        display_name="Resilience",
        category="soft_skill",
        description="Maintaining effectiveness and recovering quickly from setbacks and pressure.",
        resource_type="practice",
        url="https://hbr.org/2017/01/resilience-is-about-how-you-recharge-not-how-you-endure",
        prerequisites=(),
    ),
    "creativity": SkillResourceDescriptor(
        display_name="Creativity",
        category="soft_skill",
        description="Generating original ideas and novel approaches to complex problems.",
        resource_type="practice",
        url="https://hbr.org/topic/subject/creativity",
        prerequisites=(),
    ),
    "innovation": SkillResourceDescriptor(
        display_name="Innovation",
        category="soft_skill",
        description="Translating creative ideas into improvements in products, processes, or services.",
        resource_type="practice",
        url="https://hbr.org/topic/subject/innovation",
        prerequisites=(),
    ),
    "proactive": SkillResourceDescriptor(
        display_name="Proactivity",
        category="soft_skill",
        description="Anticipating needs and acting before issues arise rather than reacting.",
        resource_type="practice",
        url="https://hbr.org/2014/01/take-initiative-dont-be-passive",
        prerequisites=(),
    ),
    "agile": SkillResourceDescriptor(
        display_name="Agile",
        category="soft_skill",
        description="Iterative project methodology emphasising flexibility, feedback, and collaboration.",
        resource_type="course",
        url="https://www.agilealliance.org/agile101/",
        prerequisites=(),
    ),
    "scrum": SkillResourceDescriptor(
        display_name="Scrum",
        category="soft_skill",
        description="Agile framework using sprints and ceremonies to deliver value incrementally.",
        resource_type="certification",
        url="https://www.scrumalliance.org/learn-about-scrum",
        prerequisites=("agile",),
    ),
    "kanban": SkillResourceDescriptor(
        display_name="Kanban",
        category="soft_skill",
        description="Visual workflow management method for limiting work in progress and improving flow.",
        resource_type="course",
        url="https://kanbanize.com/kanban-resources",
        prerequisites=(),
    ),
    "stakeholder": SkillResourceDescriptor(
        display_name="Stakeholder Management",
        category="soft_skill",
        description="Identifying and managing relationships with people who affect or are affected by a project.",
        resource_type="course",
        url="https://hbr.org/topic/subject/stakeholder-management",
        prerequisites=(),
    ),
    "delegation": SkillResourceDescriptor(
        display_name="Delegation",
        category="soft_skill",
        description="Assigning tasks and authority to the right people to achieve results at scale.",
        resource_type="practice",
        url="https://hbr.org/2017/07/how-to-decide-which-tasks-to-delegate",
        prerequisites=(),
    ),
    "prioritization": SkillResourceDescriptor(
        display_name="Prioritization",
        category="soft_skill",
        description="Ordering work by impact and urgency to maximise value delivery.",
        resource_type="practice",
        url="https://hbr.org/2018/09/how-to-prioritize-your-work",
        prerequisites=(),
    ),
    "analytical": SkillResourceDescriptor(
        display_name="Analytical Thinking",
        category="soft_skill",
        description="Breaking down complex problems using data and structured reasoning.",
        resource_type="practice",
        url="https://hbr.org/topic/subject/critical-thinking",
        prerequisites=(),
    ),
    "storytelling": SkillResourceDescriptor(
        display_name="Storytelling",
        category="soft_skill",
        description="Communicating ideas through compelling narratives to engage and persuade.",
        resource_type="practice",
        url="https://hbr.org/topic/subject/storytelling",
        prerequisites=(),
    ),
    "presentation": SkillResourceDescriptor(
        display_name="Presentation",
        category="soft_skill",
        description="Communicating ideas effectively to an audience through structured visual delivery.",
        resource_type="practice",
        url="https://hbr.org/topic/subject/presentation-skills",
        prerequisites=(),
    ),
    "feedback": SkillResourceDescriptor(
        display_name="Feedback",
        category="soft_skill",
        description="Giving and receiving constructive input to support growth and performance improvement.",
        resource_type="practice",
        url="https://hbr.org/2019/03/the-feedback-fallacy",
        prerequisites=(),
    ),
    "entrepreneurial": SkillResourceDescriptor(
        display_name="Entrepreneurial Mindset",
        category="soft_skill",
        description="Approaching challenges with a builder's perspective and comfort with ambiguity.",
        resource_type="practice",
        url="https://hbr.org/topic/subject/entrepreneurship",
        prerequisites=(),
    ),
    "strategic": SkillResourceDescriptor(
        display_name="Strategic Thinking",
        category="soft_skill",
        description="Aligning decisions and work with long-term goals and organisational priorities.",
        resource_type="practice",
        url="https://hbr.org/2018/09/strategic-thinking",
        prerequisites=(),
    ),
    "collaborative": SkillResourceDescriptor(
        display_name="Collaboration",
        category="soft_skill",
        description="Working jointly with colleagues to achieve shared outcomes.",
        resource_type="practice",
        url="https://hbr.org/topic/subject/collaboration",
        prerequisites=(),
    ),
    "multitasking": SkillResourceDescriptor(
        display_name="Multitasking",
        category="soft_skill",
        description="Managing multiple responsibilities concurrently with effective time allocation.",
        resource_type="practice",
        url="https://hbr.org/2021/07/the-most-valuable-employees-dont-multitask",
        prerequisites=(),
    ),
    "influential": SkillResourceDescriptor(
        display_name="Influence",
        category="soft_skill",
        description="Affecting others' beliefs or actions without relying on formal authority.",
        resource_type="practice",
        url="https://hbr.org/topic/subject/influence",
        prerequisites=(),
    ),
    "motivating": SkillResourceDescriptor(
        display_name="Motivation",
        category="soft_skill",
        description="Inspiring and energising individuals and teams to perform at their best.",
        resource_type="practice",
        url="https://hbr.org/topic/subject/motivating-people",
        prerequisites=(),
    ),
    "empowering": SkillResourceDescriptor(
        display_name="Empowerment",
        category="soft_skill",
        description="Giving teams the authority, resources, and trust to own their work fully.",
        resource_type="practice",
        url="https://hbr.org/2020/01/why-empowered-teams-arent-always-the-answer",
        prerequisites=(),
    ),
    "interpersonal": SkillResourceDescriptor(
        display_name="Interpersonal Skills",
        category="soft_skill",
        description="Building positive professional relationships through emotional intelligence.",
        resource_type="practice",
        url="https://hbr.org/topic/subject/interpersonal-communication",
        prerequisites=(),
    ),
    "consensus": SkillResourceDescriptor(
        display_name="Consensus Building",
        category="soft_skill",
        description="Facilitating agreement among diverse stakeholders through inclusive dialogue.",
        resource_type="practice",
        url="https://hbr.org/2020/03/want-to-build-consensus-use-these-strategies",
        prerequisites=(),
    ),
    "conflict": SkillResourceDescriptor(
        display_name="Conflict Resolution",
        category="soft_skill",
        description="Addressing disagreements constructively to reach mutually acceptable outcomes.",
        resource_type="course",
        url="https://hbr.org/topic/subject/conflict",
        prerequisites=(),
    ),
}


def get_resource_for_skill(token: str) -> SkillResourceDescriptor | None:
    """Return the resource descriptor for a skill token, or None if not catalogued.

    The lookup is case-insensitive and normalises the token to lowercase.
    """
    return SKILL_RESOURCES.get(token.lower())


def get_resources_for_gaps(
    gaps: dict[str, list[str]],
) -> dict[str, list[dict]]:
    """Enrich a skill gaps dict with resource descriptors.

    Accepts the four-tier dict produced by extract_skill_gaps(), as well as
    legacy three-tier dicts (without the 'soft' key) for backward compatibility.

    Each gap token is enriched when a descriptor exists, or returned as
    {"token": <name>} when it is not in the catalogue.
    """
    result: dict[str, list[dict]] = {}
    for tier, tokens in gaps.items():
        enriched: list[dict] = []
        for token in tokens:
            descriptor = get_resource_for_skill(token)
            if descriptor is not None:
                enriched.append({
                    "token": token,
                    "display_name": descriptor.display_name,
                    "category": descriptor.category,
                    "description": descriptor.description,
                    "resource_type": descriptor.resource_type,
                    "url": descriptor.url,
                    "prerequisites": list(descriptor.prerequisites),
                })
            else:
                enriched.append({"token": token})
        result[tier] = enriched
    return result
