# Generated by Django 5.0.6 on 2026-06-13 01:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('templates_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('template_settings', models.JSONField(blank=True, default=dict)),
                ('custom_sections', models.JSONField(blank=True, default=list)),
                ('is_primary', models.BooleanField(default=False)),
                ('target_role', models.CharField(blank=True, max_length=200)),
                ('target_company', models.CharField(blank=True, max_length=200)),
                ('ats_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ats_analysis', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='profiles.userprofile')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resumes', to='templates_engine.template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resumes',
            },
        ),
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('change_summary', models.TextField(blank=True)),
                ('rendered_html', models.TextField(blank=True)),
                ('export_pdf_path', models.CharField(blank=True, max_length=500)),
                ('export_docx_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_versions_created', to=settings.AUTH_USER_MODEL)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='resumes.resume')),
            ],
            options={
                'db_table': 'resume_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['user', 'status'], name='resumes_user_id_4e9dad_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['created_at'], name='resumes_created_5d96d9_idx'),
        ),
        migrations.AddIndex(
            model_name='resumeversion',
            index=models.Index(fields=['resume', 'version_number'], name='resume_vers_resume__59718f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resumeversion',
            unique_together={('resume', 'version_number')},
        ),
    ]
