# Generated by Django 5.0.6 on 2026-06-13 01:03

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('resume', 'Resume'), ('cover_letter', 'Cover Letter'), ('portfolio', 'Portfolio')], max_length=20)),
                ('category', models.CharField(choices=[('ats', 'ATS'), ('executive', 'Executive'), ('professional', 'Professional'), ('technical', 'Technical'), ('corporate', 'Corporate'), ('academic', 'Academic'), ('engineering', 'Engineering'), ('management', 'Management'), ('creative', 'Creative'), ('general', 'General'), ('minimal', 'Minimal'), ('modern', 'Modern'), ('terminal', 'Terminal')], max_length=20)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_ats_optimized', models.BooleanField(default=False)),
                ('is_single_page', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('thumbnail_path', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('preview_data', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'templates',
                'indexes': [models.Index(fields=['type', 'is_active'], name='templates_type_06d973_idx'), models.Index(fields=['slug'], name='templates_slug_7b0131_idx')],
            },
        ),
    ]
