# Generated by Django 5.0.6 on 2026-07-06 07:50

from django.db import migrations
from django.core.management import call_command


def seed_templates(apps, schema_editor):
    call_command("seed_templates")


class Migration(migrations.Migration):

    dependencies = [
        ("templates_engine", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_templates, reverse_code=migrations.RunPython.noop),
    ]
