# Generated by Django 5.0.6 on 2026-06-13 01:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('resumes', '0001_initial'),
        ('templates_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('hiring_manager_name', models.CharField(blank=True, max_length=200)),
                ('hiring_manager_title', models.CharField(blank=True, max_length=200)),
                ('company_address', models.JSONField(blank=True, default=dict)),
                ('tone', models.CharField(choices=[('professional', 'Professional'), ('executive', 'Executive'), ('friendly', 'Friendly'), ('technical', 'Technical'), ('startup', 'Startup'), ('formal', 'Formal')], default='professional', max_length=20)),
                ('body_content', models.TextField(blank=True)),
                ('job_description', models.TextField(blank=True)),
                ('ai_generated', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to='profiles.userprofile')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_letters', to='resumes.resume')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cover_letters', to='templates_engine.template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cover_letters',
            },
        ),
        migrations.CreateModel(
            name='CoverLetterVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('content_snapshot', models.TextField()),
                ('rendered_html', models.TextField(blank=True)),
                ('change_summary', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cover_letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='cover_letters.coverletter')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_letter_versions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cover_letter_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='coverletter',
            index=models.Index(fields=['user', 'status'], name='cover_lette_user_id_daca96_idx'),
        ),
        migrations.AddIndex(
            model_name='coverletter',
            index=models.Index(fields=['created_at'], name='cover_lette_created_f36a24_idx'),
        ),
        migrations.AddIndex(
            model_name='coverletterversion',
            index=models.Index(fields=['cover_letter', 'version_number'], name='cover_lette_cover_l_dd503e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coverletterversion',
            unique_together={('cover_letter', 'version_number')},
        ),
    ]
