# Generated by Django 5.0.6 on 2026-06-13 01:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('templates_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('theme_settings', models.JSONField(blank=True, default=dict)),
                ('section_settings', models.JSONField(blank=True, default=dict)),
                ('custom_domain', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.TextField(blank=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=500)),
                ('og_image_path', models.CharField(blank=True, max_length=500)),
                ('analytics_provider', models.CharField(choices=[('none', 'None'), ('google_analytics', 'Google Analytics'), ('plausible', 'Plausible'), ('posthog', 'PostHog')], default='none', max_length=30)),
                ('analytics_id', models.CharField(blank=True, max_length=200)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('static_site_path', models.CharField(blank=True, max_length=500)),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='profiles.userprofile')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='portfolios', to='templates_engine.template')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portfolios',
            },
        ),
        migrations.CreateModel(
            name='PortfolioVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('theme_slug', models.CharField(blank=True, max_length=100)),
                ('section_settings', models.JSONField(blank=True, default=dict)),
                ('rendered_html', models.TextField(blank=True)),
                ('change_summary', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_versions_created', to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='portfolios.portfolio')),
            ],
            options={
                'db_table': 'portfolio_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['slug'], name='portfolios_slug_faed53_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['is_published', 'is_public'], name='portfolios_is_publ_8816a3_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioversion',
            index=models.Index(fields=['portfolio', 'version_number'], name='portfolio_v_portfol_5c4bde_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioversion',
            unique_together={('portfolio', 'version_number')},
        ),
    ]
