# Generated by Django 5.0.6 on 2026-06-13 01:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature', models.CharField(choices=[('bullet_enhance', 'Bullet Enhancement'), ('summary_generate', 'Summary Generation'), ('cover_letter_generate', 'Cover Letter Generation'), ('cover_letter_rewrite', 'Cover Letter Rewrite'), ('cover_letter_improve_tone', 'Cover Letter Tone Improvement'), ('cover_letter_improve_ats', 'Cover Letter ATS Improvement'), ('ats_analyze', 'ATS Analysis'), ('content_rewrite', 'Content Rewrite'), ('job_match', 'Job Description Matching')], max_length=30)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('gemini', 'Google Gemini')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_usage_logs',
                'indexes': [models.Index(fields=['user', 'created_at'], name='ai_usage_lo_user_id_3f9263_idx'), models.Index(fields=['created_at'], name='ai_usage_lo_created_2b4cf6_idx')],
            },
        ),
    ]
